# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

in_hull <- function(input_points, convex_hull_edges) {
    .Call(`_tcc_in_hull`, input_points, convex_hull_edges)
}

jarvis_march <- function(data) {
    .Call(`_tcc_jarvis_march`, data)
}

length_of_hull <- function(convex_hull) {
    .Call(`_tcc_length_of_hull`, convex_hull)
}

maximumdist <- function(data) {
    .Call(`_tcc_maximumdist`, data)
}

maximumdist_pair <- function(data) {
    .Call(`_tcc_maximumdist_pair`, data)
}

